### ISSUE TITLE
Fix Could not deploy artifact

### ISSUE THREAD

**Issue by bdelion** [bdelion/simple-java8-validator#11]
```yml
Run mvn -U -Dmaven.main.skip -Dunit.test.skip -Dintegration.test.skip deploy --file pom.xml
  mvn -U -Dmaven.main.skip -Dunit.test.skip -Dintegration.test.skip deploy --file pom.xml
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
    GITHUB_TOKEN: ***
```
retourne
```sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project simple-java8-validator: Failed to retrieve remote metadata fr.fifiz.training.app.java:simple-java8-validator:1.0.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata fr.fifiz.training.app.java:simple-java8-validator:1.0.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/bdelion/simple-java8-validator): Transfer failed for https://maven.pkg.github.com/bdelion/simple-java8-validator/fr/fifiz/training/app/java/simple-java8-validator/1.0.0-SNAPSHOT/maven-metadata.xml 400 Bad Request -> [Help 1]
```
