### ISSUE TITLE
Fix Cache Maven in Github Actions

### ISSUE THREAD

**Issue by bdelion** [bdelion/simple-java8-validator#9]
```yml
      - name: Cache Maven packages
        uses: actions/cache@v1
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ env.cache-name }}-
            ${{ runner.os }}-m2-
            ${{ runner.os }}-
```
retourne un message qui laisse penser qu'il ne trouve rien
```sh
Run actions/cache@v1
  with:
    path: ~/.m2/repository
    key: Linux-m2-cache-maven-dependencies-4fecd60796a4c5e2d126cbe3b53875e0330e24c89543cc407fbb0ed8ac219c53
    restore-keys: Linux-m2-cache-maven-dependencies-
  Linux-m2-
  Linux-
  
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
    cache-name: cache-maven-dependencies
Cache not found for input keys: Linux-m2-cache-maven-dependencies-4fecd60796a4c5e2d126cbe3b53875e0330e24c89543cc407fbb0ed8ac219c53, Linux-m2-cache-maven-dependencies-, Linux-m2-, Linux-.
```
